# Generated by Django 4.2.1 on 2023-05-31 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_register_users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
